---
driver:
  name: docker

provisioner:
  name: chef_solo

platforms:
  - name: debian-wheezy
  - name: debian-jessie
  - name: debian-stretch

suites:
  - name: default
    run_list:
      - recipe[bash::default]
    attributes:
