# -*- coding: utf-8 -*-
require 'serverspec'
require 'pathname'
require 'yaml'
require 'json'

# auto generated by serverspec::atribute recipe
attr_json_path = "/etc/chef/serverspec/attributes.json"

# set serverspec backend engine
set :backend, :exec

RSpec.configure do |c|
  set_property JSON.parse(File.read(attr_json_path))
  if ENV['ASK_SUDO_PASSWORD']
    require 'highline/import'
    c.sudo_password = ask("Enter sudo password: ") { |q| q.echo = false }
  else
    c.sudo_password = ENV['SUDO_PASSWORD']
  end
  c.before :all do
  end
end
